name: Check register

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: codecheckers/register:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git config --system --add safe.directory /__w/register/register
      - name: Rate before
        run: |
          curl -s -H "Authorization: token $GITHUB_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | head -20
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: |
          R -e 'options("R.cache.rootPath" = "/tmp"); codecheck::register_check(); warnings()'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Rate after
        if: always()
        run: |
          curl -s -H "Authorization: token $GITHUB_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | head -20
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
