name: Render register

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-20.04
    outputs:
      register: ${{ steps.filter.outputs.register }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check
        # https://github.com/dorny/paths-filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            register:
              - 'register.csv'
  render:
    needs: changes
    if: ${{ needs.changes.outputs.register == 'true' }}
    runs-on: ubuntu-20.04
    container:
      image: codecheckers/register:latest
      volumes:
          - "/home/runner/work/codecheckers/register:/register"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --system --add safe.directory /__w/register/register
      - name: Rate before
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit
      - name: Render
        run: |
          # R -e "sessionInfo(); cat('\n'); list.files(); cat('\n'); getwd()"
          R -e 'options("R.cache.rootPath" = "/tmp"); codecheck::register_render(); warnings()'
      - name: Rate after
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit
      - name: Update register
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: CODECHECK bot <daniel.nuest@tu-dresden.de>
          commit_message: Update register renderings
