name: Render register

on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Checkout is required before did-files-change
        uses: actions/checkout@v2
      - name: Check
        # https://github.com/dorny/paths-filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            register:
              - 'register.csv'
      - name: Render
        if: steps.filter.outputs.register == 'true'
        run: |
          echo "Run it!"
