name: Render register

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      register: ${{ steps.filter.outputs.register }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        # https://github.com/dorny/paths-filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            register:
              - 'register.csv'
  render:
    needs: changes
    if: ${{ needs.changes.outputs.register == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: codecheckers/register:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git config --system --add safe.directory /__w/register/register
      - name: Rate before
        run: |
          curl -s -H "Authorization: token $GITHUB_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | head -20
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Render
        run: |
          R -e 'options("R.cache.rootPath" = "/tmp"); codecheck::register_render(); warnings()'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Rate after
        if: always()
        run: |
          curl -s -H "Authorization: token $GITHUB_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | head -20
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Update register
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: CODECHECK bot <daniel.nuest@tu-dresden.de>
          commit_message: Update register renderings
